### ISSUE TITLE
parts of NBA stats API closed off?

### ISSUE THREAD

**Issue by EdmundKorley** [nickb1080/nba-movement#1]
Unfortunately it seems like some of the endpoints, especially `locations_getmoments`, are no longer active. The NBA seems to be restricting access to the SportsVU data as of now. The blogs and packages I've come across that depend on it seem to be no longer working.

Too bad because we wanted to do some AI stuff with the data. :(

Or I could be wrong and it is just not working for me.

**Comment by bttmly** [comment]
Yeah I left a note in the repo tagline and the readme. My best guess is that stats.com [sells this data](http://www.stats.com/sportvu/sportvu-basketball-media/) for a lot of money, and got alarmed when several blog posts went up detailing how to pull it off NBA.com, so they yanked it. I'm kicking myself for not pulling as much as I could while it was up.
